/*
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package meli
// Item struct for Item
type Item struct {
	Title string `json:"title"`
	CategoryId string `json:"category_id"`
	Price int32 `json:"price"`
	CurrencyId string `json:"currency_id"`
	AvailableQuantity string `json:"available_quantity"`
	BuyingMode string `json:"buying_mode"`
	ListingTypeId string `json:"listing_type_id"`
	Condition string `json:"condition"`
	Description string `json:"description"`
	VideoId string `json:"video_id"`
	Pictures []ItemPictures `json:"pictures"`
	Attributes []Attributes `json:"attributes,omitempty"`
	Variations []Variations `json:"variations,omitempty"`
}
