/*
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package meli
// VariationsAttributeCombinations struct for VariationsAttributeCombinations
type VariationsAttributeCombinations struct {
	Name string `json:"name,omitempty"`
	ValueId string `json:"value_id,omitempty"`
	ValueName string `json:"value_name,omitempty"`
}
