/*
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package meli
// AttributesValueStruct struct for AttributesValueStruct
type AttributesValueStruct struct {
	Number float32 `json:"number,omitempty"`
	Unit string `json:"unit,omitempty"`
}
