/*
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package meli
// AttributesValues struct for AttributesValues
type AttributesValues struct {
	Id *string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Struct *AttributesValueStruct `json:"struct,omitempty"`
}
