/*
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package meli
// Attributes struct for Attributes
type Attributes struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	ValueId *string `json:"value_id,omitempty"`
	ValueName string `json:"value_name,omitempty"`
	ValueStruct *AttributesValueStruct `json:"value_struct,omitempty"`
	Values []AttributesValues `json:"values,omitempty"`
	AttributeGroupId string `json:"attribute_group_id,omitempty"`
	AttributeGroupName string `json:"attribute_group_name,omitempty"`
}
