/*
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package meli
// ItemPictures struct for ItemPictures
type ItemPictures struct {
	Source string `json:"source,omitempty"`
}
