/*
 * MELI Markeplace SDK
 *
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package meli
// Variations struct for Variations
type Variations struct {
	Price int32 `json:"price,omitempty"`
	AttributeCombinations []VariationsAttributeCombinations `json:"attribute_combinations,omitempty"`
	AvailableQuantity int32 `json:"available_quantity,omitempty"`
	SoldQuantity int32 `json:"sold_quantity,omitempty"`
	PictureIds []string `json:"picture_ids,omitempty"`
}
